-- Run this in Supabase SQL Editor

-- 1) data_sources
create table if not exists public.data_sources (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  file_type text not null,
  file_url text not null,
  created_at timestamp with time zone default now()
);

-- 2) reports
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null,
  format text not null,
  status text not null default 'created',
  file_url text,
  created_at timestamp with time zone default now()
);

-- Minimal RLS policies (DEV ONLY)
alter table public.data_sources enable row level security;
alter table public.reports enable row level security;

-- Allow authenticated users to manage their own rows
create policy "data_sources_select_own" on public.data_sources
for select to authenticated
using (auth.uid() = user_id);

create policy "data_sources_insert_own" on public.data_sources
for insert to authenticated
with check (auth.uid() = user_id);

create policy "reports_select_own" on public.reports
for select to authenticated
using (auth.uid() = user_id);

create policy "reports_insert_own" on public.reports
for insert to authenticated
with check (auth.uid() = user_id);

-- Optional: allow delete/update own rows (commented)
-- create policy "data_sources_update_own" on public.data_sources
-- for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
-- create policy "data_sources_delete_own" on public.data_sources
-- for delete to authenticated using (auth.uid() = user_id);

-- create policy "reports_update_own" on public.reports
-- for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
-- create policy "reports_delete_own" on public.reports
-- for delete to authenticated using (auth.uid() = user_id);

-- Storage bucket:
-- Create a bucket named "uploads" and make it public for now (DEV).
